# Generated by Django 4.2.1 on 2023-06-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_subscribers_alter_subscription_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
